// --- BASE DE DADOS DAS VARIANTES (AJUSTADA) ---
const ALL_VARIANTS = {
    'aerpegasus': [ { name: "Stock", image: "images/blades/AeroPegasus.png" } ],
    'bearscratch': [ { name: "Stock", image: "images/blades/BearScratch.png" } ],
    'blackshell': [ { name: "Stock", image: "images/blades/BlackShell.png" }, { name: "ver. 2", image: "images/variantes/BlackShell_9-80B.jpeg" } ],
    'cobaltdragoon': [ { name: "Stock", image: "images/blades/CobaltDragoon.png" } ],
    'cobaltdrake': [ { name: "Stock", image: "images/blades/CobaltDrake.png" }, { name: "ver. 2", image: "images/variantes/CobaltDrake_9-60R.png" } ],
    'crimsongaruda': [ { name: "Stock", image: "images/blades/CrimsonGaruda.png" } ],
    'croccrunch': [ { name: "Stock", image: "images/blades/CrocCrunch.png" } ],
    'darthvader': [ { name: "Stock", image: "images/blades/DarthVader.png" } ],
    'dracielshield': [ { name: "Stock", image: "images/blades/DracielShield.png" } ],
    'dragoonsform': [ { name: "Stock", image: "images/blades/DragoonStorm.png" } ],
    'dranbuster': [ { name: "Stock", image: "images/blades/DranBuster.png" }, { name: "ver. 2", image: "images/variantes/DranBuster_3-70N.png" } ],
    'drandagger': [ { name: "Stock", image: "images/blades/DranDagger.png" }, { name: "ver. 2", image: "images/variantes/DranDagger_4-60R.png" }, { name: "ver. 3", image: "images/variantes/DranDagger_4-70P.png" }, { name: "ver. 4", image: "images/variantes/DranDagger_9-60LF.png" } ],
    'dransword': [ { name: "Stock", image: "images/blades/DranSword.png" }, { name: "ver. 2", image: "images/variantes/DranSword_3-80B.png" }, { name: "ver. 3", image: "images/variantes/DranSword_4-80DB.png" }, { name: "ver. 4", image: "images/variantes/2.png" }, { name: "ver. 5", image: "images/variantes/3.png" }, { name: "ver. 6", image: "images/variantes/latest.png" } ],
    'dranzerspiral': [ { name: "Stock", image: "images/blades/DranzerSpiral.png" } ],
    'drigerslash': [ { name: "Stock", image: "images/blades/DrigerSlash.png" } ],
    'generalgrievous': [ { name: "Stock", image: "images/blades/GeneralGrievous.png" } ],
    'ghostcircle': [ { name: "Stock", image: "images/blades/GhostCircle.png" }, { name: "ver. 2", image: "images/variantes/GhostCircle_4-60H.png" } ],
    'gillshark': [ { name: "Stock", image: "images/blades/GillShark.png" } ],
    'hellschain': [ { name: "Stock", image: "images/blades/HellsChain.png" }, { name: "ver. 2", image: "images/variantes/HellsChain_9-80O.png" } ],
    'hellshammer': [ { name: "Stock", image: "images/blades/HellsHammer.png" } ],
    'hellsscythe': [ { name: "Stock", image: "images/blades/HellsScythe.png" }, { name: "ver. 2", image: "images/variantes/HellsScythe_3-80F.png" }, { name: "ver. 3", image: "images/variantes/HellsScythe_4-60T.png" }, { name: "ver. 4", image: "images/variantes/HellsScythe_4-80LF.png" } ],
    'hoverwyvern': [ { name: "Stock", image: "images/blades/HoverWyvern.png" } ],
    'impactdrake': [ { name: "Stock", image: "images/blades/ImpactDrake.png" }, { name: "ver. 2", image: "images/variantes/ImpactDrake_9-60LR.png" } ],
    'knightlance': [ { name: "Stock", image: "images/blades/KnightLance.png" }, { name: "ver. 2", image: "images/variantes/KnightLance_4-60GB.png" }, { name: "ver. 3", image: "images/variantes/KnightLance_4-80HN.png" } ],
    'knightmail': [ { name: "Stock", image: "images/blades/KnightMail.png" } ],
    'knightshield': [ { name: "Stock", image: "images/blades/KnightShield.png" }, { name: "ver. 2", image: "images/variantes/KnightShield_4-60LF.png" }, { name: "ver. 3", image: "images/variantes/KnightShield_4-80T.png" }, { name: "ver. 4", image: "images/variantes/KnightShield_5-80T.png" } ],
    'leonclaw': [ { name: "Stock", image: "images/blades/LeonClaw.png" }, { name: "ver. 2", image: "images/variantes/LeonClaw_3-80HN.png" }, { name: "ver. 3", image: "images/variantes/LeonClaw_5-60P.png" } ],
    'leoncrest': [ { name: "Stock", image: "images/blades/LeonCrest.png" }, { name: "ver. 2", image: "images/variantes/LeonCrest_9-80K.png" } ],
    'lightningl-drago': [ { name: "Stock", image: "images/blades/LightningL-Drago.png" }, { name: "ver. 2", image: "images/variantes/Lightning_L-Drago_1-60F.png" } ],
    'mammothtusk': [ { name: "Stock", image: "images/blades/MammothTusk.png" } ],
    'moffgideon': [ { name: "Stock", image: "images/blades/MoffGideon.png" } ],
    'mosasaurus': [ { name: "Stock", image: "images/blades/Mosasaurus.png" } ],
    'optimusprimal': [ { name: "Stock", image: "images/blades/OptimusPrimal.png" } ],
    'optimusprime': [ { name: "Stock", image: "images/blades/OptimusPrime.png" } ],
    'phoenixfeather': [ { name: "Stock", image: "images/blades/PhoenixFeather.png" }, { name: "ver. 2", image: "images/variantes/PhoenixFeather_3-60F.png" }, { name: "ver. 3", image: "images/variantes/PhoenixFeather_4-60LF.png" } ],
    'phoenixrudder': [ { name: "Stock", image: "images/blades/PhoenixRudder.png" }, { name: "ver. 2", image: "images/variantes/PhoenixRudder_9-70G.png" } ],
    'phoenixwing': [ { name: "Stock", image: "images/blades/PhoenixWing.png" }, { name: "ver. 2", image: "images/variantes/PhoenixWing_9-60GF.png" }, { name: "ver. 3", image: "images/variantes/PhoenixWing_9-80DB.png" } ],
    'quetzalcoatlus': [ { name: "Stock", image: "images/blades/Quetzalcoatlus.png" } ],
    'rhinohorn': [ { name: "Stock", image: "images/blades/RhinoHorn.png" }, { name: "ver. 2", image: "images/variantes/RhinoHorn_5-80Q.png" } ],
    'rockleone': [ { name: "Stock", image: "images/blades/RockLeone.png" } ],
    'samuraicalibur': [ { name: "Stock", image: "images/blades/SamuraiCalibur.png" } ],
    'samuraisaber': [ { name: "Stock", image: "images/blades/SamuraiSaber.png" } ],
    'scorpiospear': [ { name: "Stock", image: "images/blades/ScorpioSpear.png" } ],
    'sharkedge': [ { name: "Stock", image: "images/blades/SharkEdge.png" }, { name: "ver. 2", image: "images/variantes/SharkEdge_3-60LF.png" }, { name: "ver. 3", image: "images/variantes/SharkEdge_3-80F.png" }, { name: "ver. 4", image: "images/variantes/SharkEdge_4-80N.png" }, { name: "ver. 5", image: "images/variantes/SharkEdge_5-60GF.png" } ],
    'sharkscale': [ { name: "Stock", image: "images/blades/SharkScale.png" } ],
    'shelterdrake': [ { name: "Stock", image: "images/blades/ShelterDrake.png" }, { name: "ver. 2", image: "images/variantes/ShelterDrake_5-70O.png" }, { name: "ver. 3", image: "images/variantes/ShelterDrake_7-80GP.png" } ],
    'shinobiknife': [ { name: "Stock", image: "images/blades/ShinobiKnife.png" } ],
    'shinobishadow': [ { name: "Stock", image: "images/blades/ShinobiShadow.png" }, { name: "ver. 2", image: "images/variantes/ShinobiShadow_3-70GP.png" }, { name: "ver. 3", image: "images/variantes/ShinobiShadow_3-80F.png" }, { name: "ver. 4", image: "images/variantes/ShinobiShadow_9-60LF.png" } ],
    'silverwolf': [ { name: "Stock", image: "images/blades/SilverWolf.png" } ],
    'sphinx-cowl': [ { name: "Stock", image: "images/blades/SphinxCowl.png" }, { name: "ver. 2", image: "images/variantes/SphinxCowl_4-80HT.png" }, { name: "ver. 3", image: "images/variantes/SphinxCowl_5-60O.png" }, { name: "ver. 4", image: "images/variantes/SphinxCowl_9-80GN.png" } ],
    'spider-man': [ { name: "Stock", image: "images/blades/Spider-Man.png" } ],
    'spinosaurus': [ { name: "Stock", image: "images/blades/Spinosaurus.png" } ],
    'stormpegasis': [ { name: "Stock", image: "images/blades/StormPegasis.png" } ],
    't.rex': [ { name: "Stock", image: "images/blades/T.Rex.png" } ],
    'tacklegoat': [ { name: "Stock", image: "images/blades/TackleGoat.png" } ],
    'thanos': [ { name: "Stock", image: "images/blades/Thanos.png" } ],
    'tricerapress': [ { name: "Stock", image: "images/blades/TriceraPress.png" } ],
    'tyrannobeat': [ { name: "Stock", image: "images/blades/TyrannoBeat.png" }, { name: "ver. 2", image: "images/variantes/TyrannoBeat_4-70Q.png" } ],
    'tyrannoroar': [ { name: "Stock", image: "images/blades/TyrannoRoar.png" } ],
    'unicornsting': [ { name: "Stock", image: "images/blades/UnicornSting.png" }, { name: "ver. 2", image: "images/variantes/UnicornSting_5-60GP.png" } ],
    'venom': [ { name: "Stock", image: "images/blades/Venom.png" } ],
    'victoryvalkyrie': [ { name: "Stock", image: "images/blades/VictoryValkyrie.png" } ],
    'vipertail': [ { name: "Stock", image: "images/blades/ViperTail.png" }, { name: "ver. 2", image: "images/variantes/ViperTail_4-60F.png" }, { name: "ver. 3", image: "images/variantes/ViperTail_5-60F.png" }, { name: "ver. 4", image: "images/variantes/ViperTail_5-70D.png" }, { name: "ver. 5", image: "images/variantes/ViperTail_5-80O.png" } ],
    'weisstiger': [ { name: "Stock", image: "images/blades/WeissTiger.png" } ],
    'whalewave': [ { name: "Stock", image: "images/blades/WhaleWave.png" }, { name: "ver. 2", image: "images/variantes/WhaleWave_4-70HN.png" }, { name: "ver. 3", image: "images/variantes/WhaleWave_5-80E.png" }, { name: "ver. 4", image: "images/variantes/WhaleWave_7-60K.png" } ],
    'wizardarrow': [ { name: "Stock", image: "images/blades/WizardArrow.png" }, { name: "ver. 2", image: "images/variantes/WizardArrow_4-60N.png" }, { name: "ver. 4", image: "images/variantes/WizardArrow_4-80GB.png" }, { name: "ver. 3", image: "images/variantes/WizardArrow_4-80N.png" }, { name: "ver. 5", image: "images/variantes/4.png" } ],
    'wizardrod': [ { name: "Stock", image: "images/blades/WizardRod.png" }, { name: "ver. 2", image: "images/variantes/WizardRod_5-70DB.png" } ],
    'wyverngale': [ { name: "Stock", image: "images/blades/WyvernGale.png" }, { name: "ver. 2", image: "images/variantes/WyvernGale_2-60S.png" }, { name: "ver. 3", image: "images/variantes/WyvernGale_3-60T.png" }, { name: "ver. 4", image: "images/variantes/WyvernGale_5-80GB.png" } ],
    'xenoxcalibur': [ { name: "Stock", image: "images/blades/XenoXcalibur.png" } ],
    'yellkong': [ { name: "Stock", image: "images/blades/YellKong.png" } ]
};

// --- BASE DE DADOS DAS PEÇAS E COMBOS ---
const ALL_PARTS = [
    { id: 'aerpegasus', name: 'AeroPegasus', type: 'blade', image: 'images/blades/AeroPegasus.png', score: 26.2, variantsId: 'aerpegasus' },
    { id: 'cobaltdragoon', name: 'CobaltDragoon', type: 'blade', image: 'images/blades/CobaltDragoon.png', score: 279, variantsId: 'cobaltdragoon' },
    { id: 'dranbuster', name: 'DranBuster', type: 'blade', image: 'images/blades/DranBuster.png', score: 16.5, variantsId: 'dranbuster' },
    { id: 'drandagger', name: 'DranDagger', type: 'blade', image: 'images/blades/DranDagger.png', score: 4.5, variantsId: 'drandagger' },
    { id: 'dransword', name: 'DranSword', type: 'blade', image: 'images/blades/DranSword.png', score: 6, variantsId: 'dransword' },
    { id: 'hellschain', name: 'HellsChain', type: 'blade', image: 'images/blades/HellsChain.png', score: 6.5, variantsId: 'hellschain' },
    { id: 'hellsscythe', name: 'HellsScythe', type: 'blade', image: 'images/blades/HellsScythe.png', score: 6.5, variantsId: 'hellsscythe' },
    { id: 'hoverwyvern', name: 'HoverWyvern', type: 'blade', image: 'images/blades/HoverWyvern.png', score: 13.5, variantsId: 'hoverwyvern' },
    { id: 'knightmail', name: 'KnightMail', type: 'blade', image: 'images/blades/KnightMail.png', score: 11.5, variantsId: 'knightmail' },
    { id: 'knightshield', name: 'KnightShield', type: 'blade', image: 'images/blades/KnightShield.png', score: 5, variantsId: 'knightshield' },
    { id: 'leonclaw', name: 'LeonClaw', type: 'blade', image: 'images/blades/LeonClaw.png', score: 4, variantsId: 'leonclaw' },
    { id: 'phoenixwing', name: 'PhoenixWing', type: 'blade', image: 'images/blades/PhoenixWing.png', score: 71, variantsId: 'phoenixwing' },
    { id: 'sharkscale', name: 'SharkScale', type: 'blade', image: 'images/blades/SharkScale.png', score: 26.5, variantsId: 'sharkscale' },
    { id: 'silverwolf', name: 'SilverWolf', type: 'blade', image: 'images/blades/SilverWolf.png', score: 28, variantsId: 'silverwolf' },
    { id: 'tyrannobeat', name: 'TyrannoBeat', type: 'blade', image: 'images/blades/TyrannoBeat.png', score: 21, variantsId: 'tyrannobeat' },
    { id: 'unicornsting', name: 'UnicornSting', type: 'blade', image: 'images/blades/UnicornSting.png', score: 8.5, variantsId: 'unicornsting' },
    { id: 'wizardarrow', name: 'WizardArrow', type: 'blade', image: 'images/blades/WizardArrow.png', score: 3.5, variantsId: 'wizardarrow' },
    { id: 'wizardrod', name: 'WizardRod', type: 'blade', image: 'images/blades/WizardRod.png', score: 262.5, variantsId: 'wizardrod' },
    { id: 'arc', name: 'Arc', type: 'blade', image: 'images/blades/Arc.png', score: 3.5 },
    { id: 'bearscratch', name: 'BearScratch', type: 'blade', image: 'images/blades/BearScratch.png', score: 2, variantsId: 'bearscratch' },
    { id: 'blackshell', name: 'BlackShell', type: 'blade', image: 'images/blades/BlackShell.png', score: 4, variantsId: 'blackshell' },
    { id: 'blast', name: 'Blast', type: 'blade', image: 'images/blades/Blast.png', score: 10 },
    { id: 'bolt', name: 'Bolt', type: 'blade', image: 'images/blades/Bolt.png', score: 4.5 },
    { id: 'brave', name: 'Brave', type: 'blade', image: 'images/blades/Brave.png', score: 4.5 },
    { id: 'brush', name: 'Brush', type: 'blade', image: 'images/blades/Brush.png', score: 2 },
    { id: 'cobaltdrake', name: 'CobaltDrake', type: 'blade', image: 'images/blades/CobaltDrake.png', score: 3.5, variantsId: 'cobaltdrake' },
    { id: 'crimsongaruda', name: 'CrimsonGaruda', type: 'blade', image: 'images/blades/CrimsonGaruda.png', score: 4.5, variantsId: 'crimsongaruda' },
    { id: 'croccrunch', name: 'CrocCrunch', type: 'blade', image: 'images/blades/CrocCrunch.png', score: 2, variantsId: 'croccrunch' },
    { id: 'dark', name: 'Dark', type: 'blade', image: 'images/blades/Dark.png', score: 2.5 },
    { id: 'darthvader', name: 'DarthVader', type: 'blade', image: 'images/blades/DarthVader.png', score: 2.5, variantsId: 'darthvader' },
    { id: 'dracielshield', name: 'DracielShield', type: 'blade', image: 'images/blades/DracielShield.png', score: 1.5, variantsId: 'dracielshield' },
    { id: 'dragoonsform', name: 'DragoonStorm', type: 'blade', image: 'images/blades/DragoonStorm.png', score: 1, variantsId: 'dragoonsform' },
    { id: 'dranzerspiral', name: 'DranzerSpiral', type: 'blade', image: 'images/blades/DranzerSpiral.png', score: 2.5, variantsId: 'dranzerspiral' },
    { id: 'drigerslash', name: 'DrigerSlash', type: 'blade', image: 'images/blades/DrigerSlash.png', score: 1.5, variantsId: 'drigerslash' },
    { id: 'eclipse', name: 'Eclipse', type: 'blade', image: 'images/blades/Eclipse.png', score: 2 },
    { id: 'flame', name: 'Flame', type: 'blade', image: 'images/blades/Flame.png', score: 1.5 },
    { id: 'generalgrievous', name: 'GeneralGrievous', type: 'blade', image: 'images/blades/GeneralGrievous.png', score: 1, variantsId: 'generalgrievous' },
    { id: 'ghostcircle', name: 'GhostCircle', type: 'blade', image: 'images/blades/GhostCircle.png', score: 2, variantsId: 'ghostcircle' },
    { id: 'gillshark', name: 'GillShark', type: 'blade', image: 'images/blades/GillShark.png', score: 2, variantsId: 'gillshark' },
    { id: 'golemrock', name: 'GolemRock', type: 'blade', image: 'images/blades/GolemRock.png', score: 1 },
    { id: 'hellshammer', name: 'HellsHammer', type: 'blade', image: 'images/blades/HellsHammer.png', score: 4.5, variantsId: 'hellshammer' },
    { id: 'hornet', name: 'Hornet', type: 'blade', image: 'images/blades/Hornet.png', score: 1 },
    { id: 'impactdrake', name: 'ImpactDrake', type: 'blade', image: 'images/blades/ImpactDrake.png', score: 5.5, variantsId: 'impactdrake' },
    { id: 'knightlance', name: 'KnightLance', type: 'blade', image: 'images/blades/KnightLance.png', score: 3.5, variantsId: 'knightlance' },
    { id: 'kraken', name: 'Kraken', type: 'blade', image: 'images/blades/Kraken.png', score: 1 },
    { id: 'leoncrest', name: 'LeonCrest', type: 'blade', image: 'images/blades/LeonCrest.png', score: 2.5, variantsId: 'leoncrest' },
    { id: 'lightningl-drago', name: 'LightningL-Drago', type: 'blade', image: 'images/blades/LightningL-Drago.png', score: 3.5, variantsId: 'lightningl-drago' },
    { id: 'mammothtusk', name: 'MammothTusk', type: 'blade', image: 'images/blades/MammothTusk.png', score: 1.5, variantsId: 'mammothtusk' },
    { id: 'moffgideon', name: 'MoffGideon', type: 'blade', image: 'images/blades/MoffGideon.png', score: 1, variantsId: 'moffgideon' },
    { id: 'mosasaurus', name: 'Mosasaurus', type: 'blade', image: 'images/blades/Mosasaurus.png', score: 1, variantsId: 'mosasaurus' },
    { id: 'optimusprimal', name: 'OptimusPrimal', type: 'blade', image: 'images/blades/OptimusPrimal.png', score: 2, variantsId: 'optimusprimal' },
    { id: 'optimusprime', name: 'OptimusPrime', type: 'blade', image: 'images/blades/OptimusPrime.png', score: 1, variantsId: 'optimusprime' },
    { id: 'phoenixfeather', name: 'PhoenixFeather', type: 'blade', image: 'images/blades/PhoenixFeather.png', score: 1.5, variantsId: 'phoenixfeather' },
    { id: 'phoenixrudder', name: 'PhoenixRudder', type: 'blade', image: 'images/blades/PhoenixRudder.png', score: 2, variantsId: 'phoenixrudder' },
    { id: 'pteraswing', name: 'PteraSwing', type: 'blade', image: 'images/blades/PteraSwing.png', score: 1.5 },
    { id: 'quetzalcoatlus', name: 'Quetzalcoatlus', type: 'blade', image: 'images/blades/Quetzalcoatlus.png', score: 1, variantsId: 'quetzalcoatlus' },
    { id: 'reaper', name: 'Reaper', type: 'blade', image: 'images/blades/Reaper.png', score: 2.5 },
    { id: 'rhinohorn', name: 'RhinoHorn', type: 'blade', image: 'images/blades/RhinoHorn.png', score: 1.5, variantsId: 'rhinohorn' },
    { id: 'rockleone', name: 'RockLeone', type: 'blade', image: 'images/blades/RockLeone.png', score: 1.5, variantsId: 'rockleone' },
    { id: 'samuraicalibur', name: 'SamuraiCalibur', type: 'blade', image: 'images/blades/SamuraiCalibur.png', score: 3, variantsId: 'samuraicalibur' },
    { id: 'samuraisaber', name: 'SamuraiSaber', type: 'blade', image: 'images/blades/SamuraiSaber.png', score: 5, variantsId: 'samuraisaber' },
    { id: 'samuraisteel', name: 'SamuraiSteel', type: 'blade', image: 'images/blades/SamuraiSteel.png', score: 1 },
    { id: 'scorpiospear', name: 'ScorpioSpear', type: 'blade', image: 'images/blades/ScorpioSpear.png', score: 8, variantsId: 'scorpiospear' },
    { id: 'sharkedge', name: 'SharkEdge', type: 'blade', image: 'images/blades/SharkEdge.png', score: 9.5, variantsId: 'sharkedge' },
    { id: 'shelterdrake', name: 'ShelterDrake', type: 'blade', image: 'images/blades/ShelterDrake.png', score: 2, variantsId: 'shelterdrake' },
    { id: 'shinobiknife', name: 'ShinobiKnife', type: 'blade', image: 'images/blades/ShinobiKnife.png', score: 1, variantsId: 'shinobiknife' },
    { id: 'shinobishadow', name: 'ShinobiShadow', type: 'blade', image: 'images/blades/ShinobiShadow.png', score: 1.5, variantsId: 'shinobishadow' },
    { id: 'spider-man', name: 'Spider-Man', type: 'blade', image: 'images/blades/Spider-Man.png', score: 1, variantsId: 'spider-man' },
    { id: 'sphinx-cowl', name: 'SphinxCowl', type: 'blade', image: 'images/blades/SphinxCowl.png', score: 1.5, variantsId: 'sphinx-cowl' },
    { id: 'spinosaurus', name: 'Spinosaurus', type: 'blade', image: 'images/blades/Spinosaurus.png', score: 1, variantsId: 'spinosaurus' },
    { id: 'stormpegasis', name: 'StormPegasis', type: 'blade', image: 'images/blades/StormPegasis.png', score: 1, variantsId: 'stormpegasis' },
    { id: 't.rex', name: 'T.Rex', type: 'blade', image: 'images/blades/T.Rex.png', score: 1, variantsId: 't.rex' },
    { id: 'tacklegoat', name: 'TackleGoat', type: 'blade', image: 'images/blades/TackleGoat.png', score: 1, variantsId: 'tacklegoat' },
    { id: 'thanos', name: 'Thanos', type: 'blade', image: 'images/blades/Thanos.png', score: 1, variantsId: 'thanos' },
    { id: 'tricerapress', name: 'TriceraPress', type: 'blade', image: 'images/blades/TriceraPress.png', score: 2.5, variantsId: 'tricerapress' },
    { id: 'tyrannoroar', name: 'TyrannoRoar', type: 'blade', image: 'images/blades/TyrannoRoar.png', score: 5, variantsId: 'tyrannoroar' },
    { id: 'venom', name: 'Venom', type: 'blade', image: 'images/blades/Venom.png', score: 2, variantsId: 'venom' },
    { id: 'victoryvalkyrie', name: 'VictoryValkyrie', type: 'blade', image: 'images/blades/VictoryValkyrie.png', score: 1, variantsId: 'victoryvalkyrie' },
    { id: 'vipertail', name: 'ViperTail', type: 'blade', image: 'images/blades/ViperTail.png', score: 2.5, variantsId: 'vipertail' },
    { id: 'weisstiger', name: 'WeissTiger', type: 'blade', image: 'images/blades/WeissTiger.png', score: 2, variantsId: 'weisstiger' },
    { id: 'whalewave', name: 'WhaleWave', type: 'blade', image: 'images/blades/WhaleWave.png', score: 6, variantsId: 'whalewave' },
    { id: 'wyverngale', name: 'WyvernGale', type: 'blade', image: 'images/blades/WyvernGale.png', score: 1.5, variantsId: 'wyverngale' },
    { id: 'xenoxcaliburius', name: 'XenoXcaliburius', type: 'blade', image: 'images/blades/XenoXcaliburius.png', score: 1 },
    { id: 'xenoxcalibur', name: 'XenoXcalibur', type: 'blade', image: 'images/blades/XenoXcalibur.png', score: 1, variantsId: 'xenoxcalibur' },
    { id: 'yellkong', name: 'YellKong', type: 'blade', image: 'images/blades/YellKong.png', score: 1.5, variantsId: 'yellkong' },

    // Ratchets
    { id: '0-70', name: '0-70', type: 'ratchet', image: 'images/ratchets/0-70.png', score: 39 }, { id: '0-80', name: '0-80', type: 'ratchet', image: 'images/ratchets/0-80.png', score: 48.5 }, { id: '1-60', name: '1-60', type: 'ratchet', image: 'images/ratchets/1-60.png', score: 3389.15 }, { id: '1-70', name: '1-70', type: 'ratchet', image: 'images/ratchets/1-70.png', score: 409.15 }, { id: '1-80', name: '1-80', type: 'ratchet', image: 'images/ratchets/1-80.png', score: 114 }, { id: '2-60', name: '2-60', type: 'ratchet', image: 'images/ratchets/2-60.png', score: 49.25 }, { id: '2-70', name: '2-70', type: 'ratchet', image: 'images/ratchets/2-70.png', score: 13 }, { id: '2-80', name: '2-80', type: 'ratchet', image: 'images/ratchets/2-80.png', score: 5 }, { id: '3-60', name: '3-60', type: 'ratchet', image: 'images/ratchets/3-60.png', score: 2580.5 }, { id: '3-70', name: '3-70', type: 'ratchet', image: 'images/ratchets/3-70.png', score: 114.15 }, { id: '3-80', name: '3-80', type: 'ratchet', image: 'images/ratchets/3-80.png', score: 88.25 }, { id: '3-85', name: '3-85', type: 'ratchet', image: 'images/ratchets/3-85.png', score: 16 }, { id: '4-50', name: '4-50', type: 'ratchet', image: 'images/ratchets/4-50.png', score: 356 }, { id: '4-55', name: '4-55', type: 'ratchet', image: 'images/ratchets/4-55.png', score: 82.15 }, { id: '4-60', name: '4-60', type: 'ratchet', image: 'images/ratchets/4-60.png', score: 178.5 }, { id: '4-70', name: '4-70', type: 'ratchet', image: 'images/ratchets/4-70.png', score: 22.5 }, { id: '4-80', name: '4-80', type: 'ratchet', image: 'images/ratchets/4-80.png', score: 28.25 }, { id: '5-60', name: '5-60', type: 'ratchet', image: 'images/ratchets/5-60.png', score: 1760.15 }, { id: '5-70', name: '5-70', type: 'ratchet', image: 'images/ratchets/5-70.png', score: 150 }, { id: '5-80', name: '5-80', type: 'ratchet', image: 'images/ratchets/5-80.png', score: 70 }, { id: '6-60', name: '6-60', type: 'ratchet', image: 'images/ratchets/6-60.png', score: 345.25 }, { id: '6-70', name: '6-70', type: 'ratchet', image: 'images/ratchets/6-70.png', score: 5 }, { id: '6-80', name: '6-80', type: 'ratchet', image: 'images/ratchets/6-80.png', score: 22.5 }, { id: '7-60', name: '7-60', type: 'ratchet', image: 'images/ratchets/7-60.png', score: 1174 }, { id: '7-70', name: '7-70', type: 'ratchet', image: 'images/ratchets/7-70.png', score: 228.25 }, { id: '7-80', name: '7-80', type: 'ratchet', image: 'images/ratchets/7-80.png', score: 17.25 }, { id: '9-60', name: '9-60', type: 'ratchet', image: 'images/ratchets/9-60.png', score: 3327.5 }, { id: '9-70', name: '9-70', type: 'ratchet', image: 'images/ratchets/9-70.png', score: 296.5 }, { id: '9-80', name: '9-80', type: 'ratchet', image: 'images/ratchets/9-80.png', score: 94 }, { id: 'm-85', name: 'M-85', type: 'ratchet', image: 'images/ratchets/M-85.png', score: 11 },

    // Bits
    { id: 'accel', name: 'Accel', type: 'bit', image: 'images/bits/Accel.png', score: 39 }, { id: 'ball', name: 'Ball', type: 'bit', image: 'images/bits/Ball.png', score: 1298.25 }, { id: 'boundspike', name: 'BoundSpike', type: 'bit', image: 'images/bits/BoundSpike.png', score: 39.5 }, { id: 'cyclone', name: 'Cyclone', type: 'bit', image: 'images/bits/Cyclone.png', score: 79 }, { id: 'diskball', name: 'DiskBall', type: 'bit', image: 'images/bits/DiskBall.png', score: 17 }, { id: 'dot', name: 'Dot', type: 'bit', image: 'images/bits/Dot.png', score: 39.5 }, { id: 'elevate', name: 'Elevate', type: 'bit', image: 'images/bits/Elevate.png', score: 1299 }, { id: 'flat', name: 'Flat', type: 'bit', image: 'images/bits/Flat.png', score: 223 }, { id: 'freeball', name: 'FreeBall', type: 'bit', image: 'images/bits/FreeBall.png', score: 716 }, { id: 'gearball', name: 'GearBall', type: 'bit', image: 'images/bits/GearBall.png', score: 35 }, { id: 'gearflat', name: 'GearFlat', type: 'bit', image: 'images/bits/GearFlat.png', score: 48.15 }, { id: 'gearneedle', name: 'GearNeedle', type: 'bit', image: 'images/bits/GearNeedle.png', score: 11.5 }, { id: 'gearpoint', name: 'GearPoint', type: 'bit', image: 'images/bits/GearPoint.png', score: 54 }, { id: 'gearrush', name: 'GearRush', type: 'bit', image: 'images/bits/GearRush.png', score: 25 }, { id: 'glide', name: 'Glide', type: 'bit', image: 'images/bits/Glide.png', score: 19.5 }, { id: 'hexa', name: 'Hexa', type: 'bit', image: 'images/bits/Hexa.png', score: 1908.15 }, { id: 'highneedle', name: 'HighNeedle', type: 'bit', image: 'images/bits/HighNeedle.png', score: 39.25 }, { id: 'hightaper', name: 'HighTaper', type: 'bit', image: 'images/bits/HighTaper.png', score: 29.25 }, { id: 'kick', name: 'Kick', type: 'bit', image: 'images/bits/Kick.png', score: 1050 }, { id: 'level', name: 'Level', type: 'bit', image: 'images/bits/Level.png', score: 1007.5 }, { id: 'lowflat', name: 'LowFlat', type: 'bit', image: 'images/bits/LowFlat.png', score: 350.15 }, { id: 'loworb', name: 'LowOrb', type: 'bit', image: 'images/bits/LowOrb.png', score: 351 }, { id: 'lowrush', name: 'LowRush', type: 'bit', image: 'images/bits/LowRush.png', score: 2011.5 }, { id: 'merge', name: 'Merge', type: 'bit', image: 'images/bits/Merge.png', score: 3 }, { id: 'metalneedle', name: 'MetalNeedle', type: 'bit', image: 'images/bits/MetalNeedle.png', score: 4.15 }, { id: 'needle', name: 'Needle', type: 'bit', image: 'images/bits/Needle.png', score: 31.5 }, { id: 'orb', name: 'Orb', type: 'bit', image: 'images/bits/Orb.png', score: 126 }, { id: 'point', name: 'Point', type: 'bit', image: 'images/bits/Point.png', score: 752.15 }, { id: 'quake', name: 'Quake', type: 'bit', image: 'images/bits/Quake.png', score: 21.5 }, { id: 'rubberaccel', name: 'RubberAccel', type: 'bit', image: 'images/bits/RubberAccel.png', score: 110.15 }, { id: 'rush', name: 'Rush', type: 'bit', image: 'images/bits/Rush.png', score: 2214 }, { id: 'spike', name: 'Spike', type: 'bit', image: 'images/bits/Spike.png', score: 19 }, { id: 'taper', name: 'Taper', type: 'bit', image: 'images/bits/Taper.png', score: 336 }, { id: 'transpoint', name: 'TransPoint', type: 'bit', image: 'images/bits/TransPoint.png', score: 24.25 }, { id: 'underneedle', name: 'UnderNeedle', type: 'bit', image: 'images/bits/UnderNeedle.png', score: 162.5 }, { id: 'unite', name: 'Unite', type: 'bit', image: 'images/bits/Unite.png', score: 169.25 }, { id: 'vortex', name: 'Vortex', type: 'bit', image: 'images/bits/Vortex.png', score: 24.15 }, { id: 'wedge', name: 'Wedge', type: 'bit', image: 'images/bits/Wedge.png', score: 301.15 }, { id: 'zap', name: 'Zap', type: 'bit', image: 'images/bits/Zap.png', score: 47 },

    // --- Peças de Chip (Scores atualizados com valores de EXEMPLO) ---
    { id: 'lockchip-dran', name: 'Dran', type: 'lockchip', image: 'images/lockchips/Dran.png', score: 5 },
    { id: 'lockchip-fox', name: 'Fox', type: 'lockchip', image: 'images/lockchips/Fox.png', score: 5 },
    { id: 'lockchip-hells', name: 'Hells', type: 'lockchip', image: 'images/lockchips/Hells.png', score: 5 },
    { id: 'lockchip-hornet', name: 'Hornet', type: 'lockchip', image: 'images/lockchips/Hornet.png', score: 5 },
    { id: 'lockchip-kraken', name: 'Kraken', type: 'lockchip', image: 'images/lockchips/Kraken.png', score: 5 },
    { id: 'lockchip-leon', name: 'Leon', type: 'lockchip', image: 'images/lockchips/Leon.png', score: 5 },
    { id: 'lockchip-perseus', name: 'Perseus', type: 'lockchip', image: 'images/lockchips/Perseus.png', score: 5 },
    { id: 'lockchip-rhino', name: 'Rhino', type: 'lockchip', image: 'images/lockchips/Rhino.png', score: 5 },
    { id: 'lockchip-sol', name: 'Sol', type: 'lockchip', image: 'images/lockchips/Sol.png', score: 5 },
    { id: 'lockchip-stag', name: 'Stag', type: 'lockchip', image: 'images/lockchips/Stag.png', score: 5 },
    { id: 'lockchip-valkyrie', name: 'Valkyrie', type: 'lockchip', image: 'images/lockchips/Valkyrie.png', score: 5 },
    { id: 'lockchip-wizard', name: 'Wizard', type: 'lockchip', image: 'images/lockchips/Wizard.png', score: 5 },

    { id: 'mainblade-arc', name: 'Arc', type: 'mainblade', image: 'images/mainblades/Arc.png', score: 10 },
    { id: 'mainblade-brave', name: 'Brave', type: 'mainblade', image: 'images/mainblades/Brave.png', score: 10 },
    { id: 'mainblade-brush', name: 'Brush', type: 'mainblade', image: 'images/mainblades/Brush.png', score: 10 },
    { id: 'mainblade-dark', name: 'Dark', type: 'mainblade', image: 'images/mainblades/Dark.png', score: 10 },
    { id: 'mainblade-fang', name: 'Fang', type: 'mainblade', image: 'images/mainblades/Fang.png', score: 10 },
    { id: 'mainblade-fort', name: 'Fort', type: 'mainblade', image: 'images/mainblades/Fort.png', score: 10 },
    { id: 'mainblade-reaper', name: 'Reaper', type: 'mainblade', image: 'images/mainblades/Reaper.png', score: 10 },
    { id: 'mainblade-volt', name: 'Volt', type: 'mainblade', image: 'images/mainblades/Volt.png', score: 10 },
    { id: 'mainblade-wriggle', name: 'Wriggle', type: 'mainblade', image: 'images/mainblades/Wriggle.png', score: 10 },
    { id: 'antler', name: 'Antler', type: 'mainblade', image: 'images/mainblades/antler.png', score: 10 }, // Peça adicionada

    { id: 'assistblade-bumper', name: 'Bumper', type: 'assistblade', image: 'images/assistblades/Bumper.png', score: 8 },
    { id: 'assistblade-charge', name: 'Charge', type: 'assistblade', image: 'images/assistblades/Charge.png', score: 8 },
    { id: 'assistblade-jaggy', name: 'Jaggy', type: 'assistblade', image: 'images/assistblades/Jaggy.png', score: 8 },
    { id: 'assistblade-round', name: 'Round', type: 'assistblade', image: 'images/assistblades/Round.png', score: 8 },
    { id: 'assistblade-slash', name: 'Slash', type: 'assistblade', image: 'images/assistblades/Slash.png', score: 8 },
    { id: 'assistblade-turn', name: 'Turn', type: 'assistblade', image: 'images/assistblades/Turn.png', score: 8 },
];

// Lista completa de combos do meta
const ALL_COMBOS = [
    { blade: 'CobaltDragoon', ratchet: '5-60', bit: 'Elevate', points: 721.75 }, { blade: 'WizardRod', ratchet: '1-60', bit: 'Hexa', points: 668.75 }, { blade: 'WizardRod', ratchet: '9-60', bit: 'Ball', points: 622.25 }, { blade: 'PhoenixWing', ratchet: '3-60', bit: 'Rush', points: 305.25 }, { blade: 'PhoenixWing', ratchet: '1-60', bit: 'Rush', points: 275.25 }, { blade: 'CobaltDragoon', ratchet: '9-60', bit: 'Elevate', points: 202.5 }, { blade: 'HoverWyvern', ratchet: '9-60', bit: 'Kick', points: 187 }, { blade: 'WizardRod', ratchet: '3-60', bit: 'Ball', points: 167 }, { blade: 'AeroPegasus', ratchet: '1-60', bit: 'Rush', points: 149.25 }, { blade: 'PhoenixWing', ratchet: '1-60', bit: 'LowRush', points: 132.5 }, { blade: 'PhoenixWing', ratchet: '3-60', bit: 'LowRush', points: 119.5 }, { blade: 'SharkScale', ratchet: '4-50', bit: 'LowRush', points: 119 }, { blade: 'SharkScale', ratchet: '3-60', bit: 'LowRush', points: 111 }, { blade: 'WizardRod', ratchet: '9-60', bit: 'Hexa', points: 107.25 }, { blade: 'SilverWolf', ratchet: '9-60', bit: 'FreeBall', points: 100.75 }, { blade: 'TyrannoBeat', ratchet: '1-60', bit: 'Rush', points: 99.75 }, { blade: 'WizardRod', ratchet: '9-60', bit: 'LowOrb', points: 97.5 }, { blade: 'AeroPegasus', ratchet: '1-60', bit: 'Kick', points: 95 }, { blade: 'SharkScale', ratchet: '1-70', bit: 'LowRush', points: 94 }, { blade: 'PhoenixWing', ratchet: '3-60', bit: 'Point', points: 86.75 }, { blade: 'SilverWolf', ratchet: '9-60', bit: 'Hexa', points: 86.75 }, { blade: 'WizardRod', ratchet: '9-60', bit: 'FreeBall', points: 86.25 }, { blade: 'SharkScale', ratchet: '1-60', bit: 'LowRush', points: 80 }, { blade: 'KnightMail', ratchet: '1-60', bit: 'Rush', points: 69.25 }, { blade: 'CobaltDragoon', ratchet: '1-60', bit: 'Elevate', points: 69.25 }, { blade: 'HoverWyvern', ratchet: '1-60', bit: 'Kick', points: 69 }, { blade: 'PhoenixWing', ratchet: '9-60', bit: 'Rush', points: 68.5 }, { blade: 'WizardRod', ratchet: '1-60', bit: 'Rush', points: 67.5 }, { blade: 'WizardRod', ratchet: '1-70', bit: 'Hexa', points: 64 }, { blade: 'WizardRod', ratchet: '3-60', bit: 'Hexa', points: 63.75 }, { blade: 'PhoenixWing', ratchet: '5-60', bit: 'Point', points: 63.25 }, { blade: 'AeroPegasus', ratchet: '3-60', bit: 'LowRush', points: 60.25 }, { blade: 'AeroPegasus', ratchet: '1-60', bit: 'LowRush', points: 59 }, { blade: 'CobaltDragoon', ratchet: '7-60', bit: 'Level', points: 58.5 }, { blade: 'PhoenixWing', ratchet: '7-60', bit: 'Rush', points: 58.25 }, { blade: 'HoverWyvern', ratchet: '1-60', bit: 'LowRush', points: 58 }, { blade: 'WizardRod', ratchet: '7-60', bit: 'Hexa', points: 56.5 }, { blade: 'AeroPegasus', ratchet: '7-60', bit: 'Rush', points: 55 }, { blade: 'AeroPegasus', ratchet: '1-60', bit: 'Level', points: 53.25 }, { blade: 'WizardRod', ratchet: '5-60', bit: 'Hexa', points: 51.5 }, { blade: 'DranBuster', ratchet: '1-60', bit: 'Rush', points: 51.5 }, { blade: 'SilverWolf', ratchet: '9-60', bit: 'Ball', points: 51 }, { blade: 'WizardRod', ratchet: '3-60', bit: 'FreeBall', points: 49.5 }, { blade: 'TyrannoBeat', ratchet: '3-60', bit: 'Rush', points: 49 }, { blade: 'AeroPegasus', ratchet: '3-60', bit: 'Rush', points: 49 }, { blade: 'PhoenixWing', ratchet: '1-60', bit: 'Point', points: 48 }, { blade: 'ScorpioSpear', ratchet: '9-60', bit: 'FreeBall', points: 48 }, { blade: 'AeroPegasus', ratchet: '7-60', bit: 'LowRush', points: 46.5 }, { blade: 'DranBuster', ratchet: '1-60', bit: 'LowFlat', points: 45.75 }, { blade: 'SilverWolf', ratchet: '3-60', bit: 'FreeBall', points: 45.5 },
];

// Lista de combos de Chip (Exemplo)
const ALL_CHIP_COMBOS = [
    { lockchip: 'Dran', mainblade: 'Brave', assistblade: 'Slash', points: 30 },
    { lockchip: 'Hells', mainblade: 'Reaper', assistblade: 'Charge', points: 28 },
    { lockchip: 'Fox', mainblade: 'Brush', assistblade: 'Round', points: 25 }
];

 // --- Traduções ---
 const translations = {
    'pt-br': {
        // Abas
        tab_meta: "META",
        tab_deck_builder: "Deck Builder",
        tab_collection: "Coleção",
        tab_settings: "Configurações",
        // Cabeçalhos das Abas
        meta_header: "Top 10 Combos do META",
        deck_builder_header: "Montador de Decks",
        collection_header: "Minha Coleção",
        settings_header: "Importar & Exportar Dados",
        // Aba Coleção
        collection_filter_label: "Mostrar Apenas os que Possuo",
        blades_section_title: "Blades", // (Ajustado)
        ratchets_section_title: "Ratchets",
        bits_section_title: "Bits",
        lockchips_section_title: "Lock Chips",
        mainblades_section_title: "Main Blades",
        assistblades_section_title: "Assist Blades",
        // Aba Deck Builder
        active_deck_label: "Deck Ativo:",
        deck_name_label: "Nome do Deck:",
        deck_name_placeholder: "Digite o nome do deck",
        add_deck_button_title: "Adicionar Novo Deck",
        delete_deck_button_title: "Deletar Deck Ativo",
        deck_placeholder_primeira: "Primeira Peça",
        deck_placeholder_selecione: "Selecione",
        deck_placeholder_ratchet: "Ratchet",
        deck_placeholder_bit: "Bit",
        deck_placeholder_mainblade: "Main Blade",
        deck_placeholder_assistblade: "Assist Blade",
        deck_score_label: "Soma:",
        deck_total_score_label: "Pontuação Total do Deck:",
        clear_deck_button: "Limpar Beyblades",
        export_deck_list_button: "Exportar Deck List",
         // Aba Configurações
         settings_description: "Salve sua coleção e decks em um arquivo (.bx) para backup ou para transferir para outro dispositivo.",
         language_settings_title: "Idioma / Language",
         export_button: "Exportar Dados (.bx)",
         import_button: "Importar Dados (.bx)",
         // Modal Seletor de Peças
         part_selector_modal_title_prefix: "Selecione:",
         part_suggestions_header: "Sugestões do META (que você possui)",
         part_chip_suggestions_header: "Sugestões de Combos (Chip)",
         part_suggestions_none: "Nenhuma sugestão encontrada com as peças que você possui (ou peças já estão em uso).",
         part_individual_header: "Peças Individuais (que você possui)",
         part_individual_none_prefix: "Nenhuma peça",
         part_individual_none_suffix: "disponível (verifique sua coleção ou peças já em uso no deck).",
         // Modal Variantes
         variant_modal_title_prefix: "Selecionar Variantes de",
         variant_modal_save_button: "Salvar",
          // Alertas e Prompts (Exemplo)
         prompt_new_deck_name: "Digite o nome do novo deck:",
         alert_cannot_delete_last_deck: "Você não pode deletar o último deck.",
         confirm_delete_deck_prefix: "Tem certeza que deseja deletar o deck \"",
         confirm_delete_deck_suffix: "\"? Esta ação não pode ser desfeita.",
         alert_deck_name_empty: "O nome do deck não pode ser vazio.",
         prompt_export_person_name: "Digite seu nome:",
         prompt_export_tournament_name: "Digite o nome do evento/torneio:",
         alert_export_deck_empty: "Seu deck está vazio ou não possui Beyblades completos para exportar. Adicione 3 Beyblades completos.",
         alert_export_copied: "Deck List copiada para o clipboard!",
         alert_export_copy_failed: "Falha ao copiar automaticamente. Copie o texto abaixo manualmente:\n\n",
         confirm_import_overwrite: "Importar este arquivo substituirá sua coleção e decks atuais. Deseja continuar?",
         alert_import_success: "Dados importados com sucesso!",
         alert_import_error: "Erro ao importar o arquivo:", // Sufixo adicionado pela função
         alert_invalid_file_format: "Formato de arquivo inválido ou dados corrompidos.",
         alert_file_read_error: "Erro ao ler o arquivo selecionado.",
         alert_save_error: "Não foi possível salvar os dados. O armazenamento pode estar cheio ou indisponível.",
         alert_suggestion_apply_error: "Não é possível aplicar esta sugestão. Uma ou mais peças já estão em uso neste deck.",
         alert_incompatible_part: "Não é possível adicionar uma peça do tipo '{partType}' a um Beyblade do tipo '{bayType}'. Selecione a primeira peça primeiro ou limpe o slot.",
         part_source_title: "Encontrado em:"
    },
    'en': {
        // Tabs
        tab_meta: "META",
        tab_deck_builder: "Deck Builder",
        tab_collection: "Collection",
        tab_settings: "Settings",
         // Tab Headers
         meta_header: "Top 10 META Combos",
         deck_builder_header: "Deck Builder",
         collection_header: "My Collection",
         settings_header: "Import & Export Data",
         // Collection Tab
         collection_filter_label: "Show Only Owned",
         blades_section_title: "Blades",
         ratchets_section_title: "Ratchets",
         bits_section_title: "Bits",
         lockchips_section_title: "Lock Chips",
         mainblades_section_title: "Main Blades",
         assistblades_section_title: "Assist Blades",
         // Deck Builder Tab
         active_deck_label: "Active Deck:",
         deck_name_label: "Deck Name:",
         deck_name_placeholder: "Enter deck name",
         add_deck_button_title: "Add New Deck",
         delete_deck_button_title: "Delete Active Deck",
         deck_placeholder_primeira: "First Part",
         deck_placeholder_selecione: "Select",
         deck_placeholder_ratchet: "Ratchet",
         deck_placeholder_bit: "Bit",
         deck_placeholder_mainblade: "Main Blade",
         deck_placeholder_assistblade: "Assist Blade",
         deck_score_label: "Sum:",
         deck_total_score_label: "Total Deck Score:",
         clear_deck_button: "Clear Beyblades",
         export_deck_list_button: "Export Deck List",
         // Settings Tab
         settings_description: "Save your collection and decks to a (.bx) file for backup or transfer to another device.",
         language_settings_title: "Idioma / Language",
         export_button: "Export Data (.bx)",
         import_button: "Import Data (.bx)",
          // Part Selector Modal
         part_selector_modal_title_prefix: "Select:",
         part_suggestions_header: "META Suggestions (Owned)",
         part_chip_suggestions_header: "Combo Suggestions (Chip)",
         part_suggestions_none: "No suggestions found with the parts you own (or parts are already in use).",
         part_individual_header: "Individual Parts (Owned)",
         part_individual_none_prefix: "No",
         part_individual_none_suffix: "parts available (check collection or parts already in use in the deck).",
         // Variant Modal
         variant_modal_title_prefix: "Select Variants for",
         variant_modal_save_button: "Save",
         // Alerts and Prompts (Example)
         prompt_new_deck_name: "Enter the name for the new deck:",
         alert_cannot_delete_last_deck: "You cannot delete the last deck.",
         confirm_delete_deck_prefix: "Are you sure you want to delete the deck \"",
         confirm_delete_deck_suffix: "\"? This action cannot be undone.",
         alert_deck_name_empty: "Deck name cannot be empty.",
         prompt_export_person_name: "Enter your name:",
         prompt_export_tournament_name: "Enter the event/tournament name:",
         alert_export_deck_empty: "Your deck is empty or does not have complete Beyblades to export. Add 3 complete Beyblades.",
         alert_export_copied: "Deck List copied to clipboard!",
         alert_export_copy_failed: "Failed to copy automatically. Please copy the text below manually:\n\n",
         confirm_import_overwrite: "Importing this file will overwrite your current collection and decks. Continue?",
         alert_import_success: "Data imported successfully!",
         alert_import_error: "Error importing file:", // Suffix added by function
         alert_invalid_file_format: "Invalid file format or corrupted data.",
         alert_file_read_error: "Error reading the selected file.",
         alert_save_error: "Could not save data. Storage might be full or unavailable.",
         alert_suggestion_apply_error: "Cannot apply this suggestion. One or more parts are already in use in this deck.",
         alert_incompatible_part: "Cannot add part of type '{partType}' to a Beyblade of type '{bayType}'. Select the first part first or clear the slot.",
         part_source_title: "Found in:"
    }
};

// --- Mapeamento de Peças para Produtos (Exemplos Iniciais) ---
const PART_SOURCES = {
    // Blades
    'aerpegasus': ["AeroPegasus 3-70A"],
    'dransword': ["BX-01 Starter DranSword 3-60F", "DranSword 3-80B", "DranSword 4-80DB"],
    'hellsscythe': ["BX-02 Starter HellsScythe 4-60T", "HellsScythe 3-80B", "HellsScythe 3-80F", "HellsScythe 4-80LF"],
    'wizardarrow': ["BX-03 Starter WizardArrow 4-80B", "BX-05 Booster WizardArrow 4-60N"],
    'knightshield': ["BX-04 Starter KnightShield 3-80N", "BX-06 Booster KnightShield 3-60LF"],
    'cobaltdrake': ["CobaltDrake 4-60F", "CobaltDrake 9-60R"],
    'dranbuster': ["Buster Dran 5-70DB", "DranBuster 1-60A", "DranBuster 3-70N"],
    'drandagger': ["Dagger Dran 4-70Q", "DranDagger 2-80GP", "DranDagger 4-60R", "DranDagger 4-70P", "DranDagger 9-60LF"],
    'bearscratch': ["BearScratch 5-60F"],
    'blackshell': ["BlackShell 4-60D", "BlackShell 9-80B"],
    'crimsongaruda': ["CrimsonGaruda 4-70TP"],
    'croccrunch': ["CrocCrunch 2-60Q", "Bite Croc 3-60LF"],
    'ghostcircle': ["GhostCircle 0-80GB", "GhostCircle 4-60H"],
    'hellshammer': ["HellsHammer 3-70H"],
    'impactdrake': ["ImpactDrake 7-80GP", "ImpactDrake 9-60LR"],
    'knightlance': ["KnightLance 3-60LF", "KnightLance 4-60GB", "KnightLance 4-80HN"],
    'leoncrest': ["LeonCrest 7-60GN", "LeonCrest 9-80K"],
    'phoenixfeather': ["PhoenixFeather 2-60N", "PhoenixFeather 3-60F", "PhoenixFeather 4-60LF"],
    'phoenixrudder': ["PhoenixRudder 4-70LF", "PhoenixRudder 9-70G"],
    'phoenixwing': ["PhoenixWing 5-80H", "PhoenixWing 9-60GF", "PhoenixWing 9-80DB"],
    'rhinohorn': ["RhinoHorn 3-80S", "RhinoHorn 5-80Q"],
    'samuraicalibur': ["SamuraiCalibur 6-70M"],
    'samuraisaber': ["SamuraiSaber 2-70L"],
    'scorpiospear': ["ScorpioSpear 0-70Z"],
    'sharkedge': ["SharkEdge 1-60Q", "SharkEdge 3-60LF", "SharkEdge 3-80F", "SharkEdge 4-80N", "SharkEdge 5-60GF", "Maguro Edge 3-60LF"],
    'shelterdrake': ["ShelterDrake 3-60D", "ShelterDrake 5-70O", "ShelterDrake 7-80GP"],
    'shinobiknife': ["ShinobiKnife 4-60LF", "Knife Shinobi 4-80HN"],
    'shinobishadow': ["ShinobiShadow 1-80MN", "ShinobiShadow 3-70GP", "ShinobiShadow 3-80F", "ShinobiShadow 9-60LF"],
    'sphinx-cowl': ["SphinxCowl 1-80GF", "SphinxCowl 4-80HT", "SphinxCowl 5-60O", "SphinxCowl 9-80GN"],
    'tacklegoat': ["TackleGoat 7-70T", "Tackle Goat 2-70N"],
    'tricerapress': ["TriceraPress M-85BS"],
    'tyrannobeat': ["TyrannoBeat 3-60S", "TyrannoBeat 4-70Q"],
    'tyrannoroar': ["Roar Tyranno 9-60GF", "TyrannoRoar 1-70L"],
    'unicornsting': ["UnicornSting 3-70D", "UnicornSting 5-60GP", "Sting Unicorn 4-60P"],
    'vipertail': ["ViperTail 3-80HN", "ViperTail 4-60F", "ViperTail 5-60F", "ViperTail 5-70D", "ViperTail 5-80O"],
    'weisstiger': ["WeissTiger 3-60U"],
    'whalewave': ["WhaleWave 3-80GB", "WhaleWave 4-70HN", "WhaleWave 5-80E", "WhaleWave 7-60K"],
    'wizardrod': ["WizardRod 1-60R", "WizardRod 5-70DB"],
    'wyverngale': ["WyvernGale 0-80C", "WyvernGale 2-60S", "WyvernGale 3-60T", "WyvernGale 5-80GB"],
    'yellkong': ["Yell Kong 3-60GB"],

    // Ratchets
    '0-70': ["ScorpioSpear 0-70Z"],
    '0-80': ["GhostCircle 0-80GB"],
    '1-60': ["DranBuster 1-60A", "GolemRock 1-60UN", "Lightning L-Drago 1-60F (Rapid-Hit Type)", "Lightning L-Drago 1-60F (Upper Type)", "Miles Morales 1-60GN", "Red Hulk 1-80R"],
    '1-70': ["TyrannoRoar 1-70L"],
    '1-80': ["ShinobiShadow 1-80MN", "SphinxCowl 1-80GF", "T. Rex 1-80GB"],
    '2-60': ["Antler Stag B 2-60HN", "WyvernGale 2-60S", "VictoryValkyrie 2-60RA"],
    '2-70': ["SamuraiSaber 2-70L", "Tackle Goat 2-70N"],
    '2-80': ["DranDagger 2-80GP", "MammothTusk 2-80E", "WyvernHover 2-80GN"],
    '3-60': ["DranSword 3-60F", "Bite Croc 3-60LF", "KnightLance 3-60LF", "KnightShield 3-60LF", "Optimus Primal 3-60F", "PhoenixFeather 3-60F", "SharkEdge 3-60LF", "Spider-Man 3-60F", "The Mandalorian 3-60F", "Trypio 3-60N", "TyrannoBeat 3-60S", "WeissTiger 3-60U", "Bumblebee 3-60GP"],
    '3-70': ["AeroPegasus 3-70A", "HellsHammer 3-70H", "ShinobiShadow 3-70GP", "UnicornSting 3-70D", "DranBuster 3-70N", "StormPegasis 3-70RA"],
    '3-80': ["DranSword 3-80B", "HellsScythe 3-80B", "HellsScythe 3-80F", "KnightShield 3-80N", "LeonClaw 3-80HN", "Moff Gideon 3-80N", "RhinoHorn 3-80S", "SharkEdge 3-80F", "ShinobiShadow 3-80F", "Starscream 3-80N", "Talon Ptera 3-80B", "Venom 3-80N", "ViperTail 3-80HN", "DranzerSpiral 3-80T", "General Grievous 3-80HN"],
    '3-85': ["HellsArc T3-85O", "Hover Wyvern 3-85N", "KnightMail 3-85BS", "Spinosaurus 3-85A", "Wriggle Kraken S 3-85O"],
    '4-50': ["SharkScale 4-50UF"],
    '4-55': ["Quetzalcoatlus 4-55D", "RhinoReaper C4-55D", "WizardArc R4-55LO"],
    '4-60': ["DranDagger 4-60R", "HellsScythe 4-60T", "WizardArrow 4-60N", "KnightShield 4-60LF", "ShinobiKnife 4-60LF", "ViperTail 4-60F", "CobaltDrake 4-60F", "Thanos 4-60P", "Darth Vader 4-60P", "Obi-Wan Kenobi 4-60P", "Optimus Prime 4-60P", "DragoonStorm 4-60RA"],
    '4-70': ["Dagger Dran 4-70Q", "DranDagger 4-70P", "Gill Shark 4-70O", "PhoenixRudder 4-70LF", "TyrannoBeat 4-70Q", "WhaleWave 4-70HN", "Captain America 4-70GB"],
    '4-80': ["Arrow Wizard 4-80O", "DrigerSlash 4-80P", "HellsScythe 4-80LF", "KnightLance 4-80HN", "SharkEdge 4-80N", "SphinxCowl 4-80HT", "Steel Samurai 4-80T", "WizardArrow 4-80B", "WizardArrow 4-80GB", "WizardArrow 4-80N", "Chewbacca 4-80LF", "Iron Man 4-80B", "Luke Skywalker 4-80B", "Megatron 4-80B", "DranSword 4-80DB", "Knife Shinobi 4-80HN", "Strike Hawk 4-80LF"],
    '5-60': ["BearScratch 5-60F", "LeonClaw 5-60P", "SharkEdge 5-60GF", "UnicornSting 5-60GP"],
    '5-70': ["Buster Dran 5-70DB", "ShelterDrake 5-70O", "ViperTail 5-70D", "WizardRod 5-70DB"],
    '5-80': ["PhoenixWing 5-80H", "RhinoHorn 5-80Q", "SphinxCowl 5-60O", "ViperTail 5-80O", "WhaleWave 5-80E", "Shockwave 5-80O", "Very Berry Bomb 5-80GB"],
    '6-60': ["OrochiCluster 6-60LF"],
    '6-70': ["SamuraiCalibur 6-70M"],
    '6-80': ["Rock Leone 6-80GN"],
    '7-60': ["DracielShield 7-60D", "LeonCrest 7-60GN", "Fort Hornet R 7-60T", "WhaleWave 7-60K"],
    '7-70': ["GoatTackle 7-70T", "Tackle Goat 2-70N"],
    '7-80': ["ImpactDrake 7-80GP", "ShelterDrake 7-80GP"],
    '9-60': ["DranDagger 9-60LF", "ImpactDrake 9-60LR", "LeonCrest 9-80K", "PhoenixWing 9-60GF", "ShinobiShadow 9-60LF", "Mosasaurus 9-60U", "Roar Tyranno 9-60GF"],
    '9-70': ["FoxBrush J9-70GR", "PhoenixRudder 9-70G"],
    '9-80': ["BlackShell 9-80B", "HellsChain 9-80O", "SphinxCowl 9-80GN", "Green Goblin 9-80HT"],
    'm-85': ["TriceraPress M-85BS"],

    // Bits
    'accel': ["AeroPegasus 3-70A", "DranBuster 1-60A", "LeonFang T4-60A"],
    'ball': ["DranSword 3-80B", "HellsScythe 3-80B", "WizardArrow 4-80B", "Iron Man 4-80B", "Luke Skywalker 4-80B", "Megatron 4-80B", "BlackShell 9-80B", "Talon Ptera 3-80B"],
    'boundspike': ["KnightMail 3-85BS", "TriceraPress M-85BS"],
    'cyclone': ["CobaltDragoon 2-60C", "WyvernGale 0-80C"],
    'diskball': ["Buster Dran 5-70DB", "DranSword 4-80DB", "FoxBrush J0-80DB", "PhoenixWing 9-80DB", "WizardRod 5-70DB"],
    'dot': ["BlackShell 4-60D", "DracielShield 7-60D", "Quetzalcoatlus 4-55D", "RhinoReaper C4-55D", "ShelterDrake 3-60D", "UnicornSting 3-70D", "ViperTail 5-70D"],
    'elevate': ["LeonClaw 0-80E", "MammothTusk 2-80E", "WhaleWave 5-80E"],
    'flat': ["DranSword 3-60F", "CobaltDrake 4-60F", "BearScratch 5-60F", "HellsScythe 3-80F", "Lightning L-Drago 1-60F (Rapid-Hit Type)", "Lightning L-Drago 1-60F (Upper Type)", "Optimus Primal 3-60F", "PhoenixFeather 3-60F", "SharkEdge 3-80F", "ShinobiShadow 3-80F", "Spider-Man 3-60F", "The Mandalorian 3-60F", "ViperTail 4-60F", "ViperTail 5-60F"],
    'freeball': ["SilverWolf 3-80FB"],
    'gearball': ["WizardArrow 4-80GB", "KnightLance 4-60GB", "Captain America 4-70GB", "GhostCircle 0-80GB", "T. Rex 1-80GB", "WhaleWave 3-80GB", "WyvernGale 5-80GB", "Yell Kong 3-60GB", "Very Berry Bomb 5-80GB"],
    'gearflat': ["PhoenixWing 9-60GF", "SharkEdge 5-60GF", "SphinxCowl 1-80GF", "XenoXcalibur 3-60GF", "Roar Tyranno 9-60GF", "HellsBrave J3-60GF", "SamuraiSteel 5-70GF"],
    'gearneedle': ["LeonCrest 7-60GN", "SphinxCowl 9-80GN", "Miles Morales 1-60GN", "Rock Leone 6-80GN", "WyvernHover 2-80GN"],
    'gearpoint': ["Bumblebee 3-60GP", "DranDagger 2-80GP", "ImpactDrake 7-80GP", "ShelterDrake 7-80GP", "ShinobiShadow 3-70GP", "UnicornSting 5-60GP"],
    'gearrush': ["FoxBrush J9-70GR"],
    'hexa': ["GhostCircle 4-60H"],
    'highneedle': ["Antler Stag B 2-60HN", "General Grievous 3-80HN", "KnightLance 4-80HN", "LeonClaw 3-80HN", "Knife Shinobi 4-80HN", "ViperTail 3-80HN", "WhaleWave 4-70HN"],
    'hightaper': ["HellsChain 5-60HT", "SphinxCowl 4-80HT", "Green Goblin 9-80HT"],
    'kick': ["DranArc S2-70K", "LeonCrest 9-80K", "HellsReaper T4-70K", "WhaleWave 7-60K"],
    'lowflat': ["Bite Croc 3-60LF", "DranDagger 9-60LF", "HellsScythe 4-80LF", "KnightLance 3-60LF", "KnightShield 4-60LF", "Maguro Edge 3-60LF", "OrochiCluster 6-60LF", "PhoenixFeather 4-60LF", "PhoenixRudder 4-70LF", "SharkEdge 3-60LF", "ShinobiKnife 4-60LF", "ShinobiShadow 9-60LF", "Strike Hawk 4-80LF", "Chewbacca 4-80LF"],
    'lowrush': ["ImpactDrake 9-60LR"],
    'merge': ["SamuraiCalibur 6-70M"],
    'metalneedle': ["ShinobiShadow 1-80MN"],
    'needle': ["KnightShield 3-80N", "WizardArrow 4-60N", "WizardArrow 4-80N", "DranBuster 3-70N", "Hover Wyvern 3-85N", "Moff Gideon 3-80N", "PhoenixFeather 2-60N", "Starscream 3-80N", "Stone Mont Blanc 3-80N", "Tackle Goat 2-70N", "Trypio 3-60N", "Venom 3-80N"],
    'orb': ["Arrow Wizard 4-80O", "HellsChain 9-80O", "Gill Shark 4-70O", "ShelterDrake 5-70O", "SphinxCowl 5-60O", "ViperTail 5-80O", "Wriggle Kraken S 3-85O", "HellsArc T3-85O"],
    'point': ["DrigerSlash 4-80P", "LeonClaw 5-60P", "DranDagger 4-70P", "Sting Unicorn 4-60P", "Darth Vader 4-60P", "Obi-Wan Kenobi 4-60P", "Optimus Prime 4-60P", "Thanos 4-60P"],
    'quake': ["CrocCrunch 2-60Q", "Dagger Dran 4-70Q", "RhinoHorn 5-80Q", "SharkEdge 1-60Q", "TyrannoBeat 4-70Q"],
    'rush': ["CobaltDrake 9-60R", "DranDagger 4-60R", "Red Hulk 1-80R", "WizardRod 1-60R"],
    'spike': ["RhinoHorn 3-80S", "Savage Bear 3-60S", "WyvernGale 2-60S"],
    'taper': ["HellsScythe 4-60T", "KnightShield 4-80T", "KnightShield 5-80T", "DranzerSpiral 3-80T", "Fort Hornet R 7-60T", "Steel Samurai 4-80T", "Tusk Mammoth 3-60T", "WizardArrow 3-60T", "WyvernGale 3-60T", "GoatTackle 7-70T"],
    'transpoint': ["CrimsonGaruda 4-70TP"],
    'unite': ["WeissTiger 3-60U", "FoxBrush J2-60U", "Mosasaurus 9-60U"],
    'underneedle': ["GolemRock 1-60UN"],
    'vortex': ["DranBrave S6-60V", "ValkyrieVolt S4-70V"],
    'wedge': ["PerseusDark B6-80W"],
    'zap': ["ScorpioSpear 0-70Z"],
    'rubberaccel': ["DragoonStorm 4-60RA", "StormPegasis 3-70RA", "VictoryValkyrie 2-60RA"],

};

